server:
 port: 8761

 
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false

spring:
  application:
    name: SERVICE-REGISTRY

eureka:
  instance:
    hostname: localhost
    nonSecurePort: ${server.port}
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/