spring :
  datasource :
    url : jdbc:mysql://127.0.0.1:3306/practice?useSSL=false
    username : root
    password : Ak98447245

  jpa :
   show-sql : true
   properties :
    hibernate :
      dailect : org.hibernate.dialect.MySQLMyISAMDialect
   hibernate :
    ddl-auto : update
    
  application:
   name: DEPARTMENT-SERVICE
  zipkin:
    base-url: http://localhost:9411/ 
    
server : 
  port : 3212
 
 
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#      
#  instance:
#    hostname: localhost