server:
  port: 9193
  
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/akshayhavale/config-server
          default-label: main
          clone-on-start: true