spring :
  datasource :
    url : jdbc:mysql://127.0.0.1:3306/practice?useSSL=false
    username : root
    password : Ak98447245

  jpa :
   show-sql : true
   properties :
    hibernate :
      dailect : org.hibernate.dialect.MySQLMyISAMDialect
   hibernate :
    ddl-auto : update
    
  application:
   name: USER-SERVICE
  zipkin:
   base-url: http://localhost:9411/ 
   
#   moving this to bootstrap.yml
#  cloud:
#    config:
#      enabled: true
#      uri: http://localhost/9193
#   
   
server : 
  port : 3213
  
# Earlier without connecting service registry 
#department:
#  Service:
#   url : "http://localhost:3212/department"

# with connecting service registry


   
department:
  Service:
   url : "http://DEPARTMENT-SERVICE/department"
   
# moving this to handle config-server from bootstrap.yml it bootstraps application context and application context start using application.yml
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#      
#  instance:
#    hostname: localhost